# main.py (c) 2026 Evergold <261058386+Evergold@users.noreply.github.com>
# Licensed under the MIT License (see LICENSE for details)

from fastapi import FastAPI, Request, BackgroundTasks
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
import os
from pydantic import BaseModel
from typing import List
import litellm
import yaml
import httpx
import subprocess
import asyncio
import json
from server.rag import rag_store

subconscious_state = {}

app = FastAPI(title="Verdant Beech API", description="Backend for the Cartography Agent")
OLLAMA_URL = "http://localhost:11434"

# Allow CORS for development (Vite dev server)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- API Endpoints ---
@app.get("/api/health")
async def health_check():
    return {"status": "ok"}

@app.get("/api/status/{project_id}")
async def get_background_status(project_id: str):
    return subconscious_state.get(project_id, {"gathering_thoughts": False, "lost_in_revery": False})

# --- Auto Setup & Upgrade ---
setup_status = {"in_progress": False, "updated": False}

async def auto_setup_models():
    setup_status["in_progress"] = True
    setup_status["updated"] = False
    models_to_pull = ["ollama_chat/gemma4:e4b".split("/")[-1], "embeddinggemma"]
    
    try:
        async with httpx.AsyncClient() as client:
            for model in models_to_pull:
                async with client.stream("POST", f"{OLLAMA_URL}/api/pull", json={"model": model, "stream": True}, timeout=None) as response:
                    async for line in response.aiter_lines():
                        if line:
                            try:
                                data = json.loads(line)
                                if data.get("status") == "downloading" and data.get("completed", 0) > 0:
                                    setup_status["updated"] = True
                            except:
                                pass
    except Exception as e:
        print(f"[SETUP] Error checking updates: {e}")
    finally:
        setup_status["in_progress"] = False

@app.on_event("startup")
async def on_startup():
    import asyncio
    asyncio.create_task(auto_setup_models())

@app.get("/api/setup/status")
async def get_setup_status():
    return setup_status

# --- YAML Model Configuration ---
MODELS_YAML_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models.yaml")
DEFAULT_MODELS_YAML = """# Verdant Beech - Model Configuration
# This file is automatically generated. Add or modify LiteLLM compatible models here.

assistant_models:
  - id: "ollama_chat/gemma4:e4b"
    label: "Gemma 4 (4.5B)"
  - id: "gemini/gemini-3.5-flash"
    label: "Gemini 3.5 Flash"
  - id: "gemini/gemini-3.1-pro"
    label: "Gemini 3.1 Pro"
  - id: "ollama_chat/gemma4:e2b"
    label: "Gemma 4 (2.3B)"
  # Template for other providers:
  # - id: "openai/gpt-5.6-sol"
  #   label: "GPT-5.6 Sol"
  # - id: "anthropic/claude-sonnet-5"
  #   label: "Claude Sonnet 5"
  # - id: "groq/llama-4-maverick"
  #   label: "Llama 4 Maverick (Groq)"

image_models:
  - id: "gemini/imagen-4.0-generate"
    label: "Imagen 4"
    tier: 2
    capabilities: ["One-Shot", "Photorealism"]
  - id: "gemini/nano-banana-pro"
    label: "Nano Banana Pro"
    tier: 1
    capabilities: ["Iterative", "Consistency"]
  - id: "gemini/nano-banana-2"
    label: "Nano Banana 2"
    tier: 0
    capabilities: ["Iterative", "Rapid"]
  # Template for other image providers:
  # - id: "openai/gpt-image-2"
  #   label: "GPT Image 2"
  #   tier: 1
  #   capabilities: ["General"]
  # - id: "huggingface/black-forest-labs/FLUX.2"
  #   label: "FLUX.2"
  #   tier: 1
  #   capabilities: ["Optics"]
  # - id: "bedrock/amazon.titan-image-generator-v1"
  #   label: "Amazon Titan"
  #   tier: 0
  #   capabilities: ["Enterprise"]

embedding_models:
  - id: "ollama/embeddinggemma"
    label: "EmbeddingGemma (Ollama)"
  # Template for other embedding providers:
  # - id: "ollama/paraphrase-multilingual-MiniLM-L12-v2"
  #   label: "Multilingual MiniLM (Ollama)"
  # - id: "gemini/text-embedding-004"
  #   label: "Gemini Text Embedding 004"
  # - id: "openai/text-embedding-3-large"
  #   label: "OpenAI Text Embedding 3 Large"
"""

def ensure_models_yaml():
    if not os.path.exists(MODELS_YAML_PATH):
        with open(MODELS_YAML_PATH, "w") as f:
            f.write(DEFAULT_MODELS_YAML)

ensure_models_yaml()

@app.get("/api/models")
async def get_models():
    try:
        with open(MODELS_YAML_PATH, "r") as f:
            return yaml.safe_load(f)
    except Exception as e:
        return {"error": str(e)}

# --- Project Management Configuration ---
PROJECTS_YAML_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "projects.yaml")
import uuid

def generate_default_projects():
    pid = str(uuid.uuid4())
    return {
        "active_project": pid,
        "projects": {
            pid: {
                "name": "Untitled Project",
                "selectedModel": "ollama_chat/gemma4:e4b",
                "chroma_collection": f"memory_{pid}",
                "revery_profile": []
            }
        }
    }

def ensure_projects_yaml():
    if not os.path.exists(PROJECTS_YAML_PATH):
        with open(PROJECTS_YAML_PATH, "w") as f:
            yaml.dump(generate_default_projects(), f)

ensure_projects_yaml()

def load_projects():
    try:
        with open(PROJECTS_YAML_PATH, "r") as f:
            data = yaml.safe_load(f)
            if not data or "projects" not in data:
                return generate_default_projects()
            return data
    except:
        return generate_default_projects()

def save_projects(data):
    with open(PROJECTS_YAML_PATH, "w") as f:
        yaml.dump(data, f)

@app.get("/api/projects")
async def get_projects():
    return load_projects()

class CreateProjectRequest(BaseModel):
    name: str

@app.post("/api/projects")
async def create_project(req: CreateProjectRequest):
    data = load_projects()
    
    # Auto-increment name if it already exists to preserve uniqueness constraint
    base_name = req.name.strip()
    new_name = base_name
    counter = 2
    existing_names = [p["name"].lower() for p in data["projects"].values()]
    
    while new_name.lower() in existing_names:
        new_name = f"{base_name} {counter}"
        counter += 1

    pid = str(uuid.uuid4())
    data["projects"][pid] = {
        "name": new_name,
        "selectedModel": "ollama_chat/gemma4:e4b",
        "chroma_collection": f"memory_{pid}",
        "revery_profile": []
    }
    data["active_project"] = pid
    save_projects(data)
    return {"status": "success", "id": pid}

class ActiveProjectRequest(BaseModel):
    id: str

@app.post("/api/projects/active")
async def set_active_project(req: ActiveProjectRequest):
    data = load_projects()
    if req.id in data["projects"]:
        data["active_project"] = req.id
        save_projects(data)
        return {"status": "success"}
    return {"error": "Project not found"}

class RenameProjectRequest(BaseModel):
    name: str

@app.post("/api/projects/rename")
async def rename_project(req: RenameProjectRequest):
    data = load_projects()
    active_id = data["active_project"]
    
    # Check uniqueness
    new_name = req.name.strip()
    for pid, proj in data["projects"].items():
        if pid != active_id and proj["name"].lower() == new_name.lower():
            return {"error": "A project with this name already exists."}
            
    if active_id in data["projects"]:
        data["projects"][active_id]["name"] = new_name
        save_projects(data)
        return {"status": "success"}
    return {"error": "Project not found"}

@app.delete("/api/projects/{project_id}")
async def delete_project(project_id: str):
    data = load_projects()
    if project_id in data["projects"]:
        del data["projects"][project_id]
        
        if len(data["projects"]) == 0:
            # Recreate a default project if the last one was deleted
            new_pid = str(uuid.uuid4())
            data["projects"][new_pid] = {
                "name": "Untitled Project",
                "selectedModel": "ollama_chat/gemma4:e4b",
                "chroma_collection": f"memory_{new_pid}",
                "revery_profile": []
            }
            data["active_project"] = new_pid
        elif data["active_project"] == project_id:
            data["active_project"] = list(data["projects"].keys())[0]
            
        save_projects(data)
        
        # Here we could also delete the chroma_db collection for this project.
        try:
            from server.rag import rag_store
            rag_store.client.delete_collection(f"memory_{project_id}")
        except:
            pass
            
        return {"status": "success"}
    return {"error": "Project not found"}

class StateRequest(BaseModel):
    key: str
    value: str

@app.post("/api/projects/state")
async def update_project_state(req: StateRequest):
    data = load_projects()
    active_id = data["active_project"]
    if active_id in data["projects"]:
        data["projects"][active_id][req.key] = req.value
        save_projects(data)
        return {"status": "success"}
    return {"error": "Active project not found"}

# --- Agent / Litellm Stubs ---
class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    model_name: str = "ollama_chat/gemma4:e4b"
    reasoning: str | None = None
    project_id: str | None = None

import time

async def compact_memory(project_id: str, old_messages: list, model_name: str, start_idx: int, end_idx: int):
    if not old_messages:
        return
        
    if project_id not in subconscious_state:
        subconscious_state[project_id] = {"gathering_thoughts": False, "lost_in_revery": False}
    subconscious_state[project_id]["gathering_thoughts"] = True
    
    try:
        from litellm import acompletion
        prompt = "CRITICAL INSTRUCTION: Act as a highly deterministic, non-creative summarization engine. Do NOT output any <think> tags, reasoning blocks, or internal monologue. Output ONLY the literal, factual final summary without embellishment.\n\n"
        prompt += "EXAMPLE INPUT:\nUSER: Let's make the mountains spiky.\nASSISTANT: Done.\nEXAMPLE OUTPUT: The user decided to make the mountains spiky.\n\n"
        prompt += "Summarize the following conversation segment into a single, concise sentence focusing on decisions made, user preferences, and cartography progress:\n\n"
        for msg in old_messages:
            role = msg["role"] if isinstance(msg, dict) else msg.role
            content = msg["content"] if isinstance(msg, dict) else msg.content
            prompt += f"{str(role).upper()}: {str(content)}\n"
        
        res = await acompletion(
            model=model_name,
            messages=[{"role": "user", "content": prompt}],
            max_tokens=150,
            reasoning_effort="low",
            num_ctx=1024,
            drop_params=True
        )
        summary = res.choices[0].message.content.strip()
        
        prompt_tokens = getattr(res.usage, 'prompt_tokens', 0) if hasattr(res, 'usage') and res.usage else 0
        if isinstance(prompt_tokens, int) and prompt_tokens > 900:
            print(f"[MEMORY WARNING] Summarizer prompt tokens ({prompt_tokens}) approaching context limit (1024). Truncation risk!")
        
        from server.rag import rag_store
        import uuid
        mem_collection = rag_store.client.get_or_create_collection(
            name=f"memory_{project_id}",
            embedding_function=rag_store.embedding_function
        )
        mem_collection.upsert(
            documents=[summary],
            metadatas=[{"type": "episodic_summary", "start_idx": start_idx, "end_idx": end_idx, "timestamp": time.time()}],
            ids=[str(uuid.uuid4())]
        )
        print(f"[MEMORY MANAGER] Compacted {len(old_messages)} messages into ChromaDB for project {project_id}.")
        
        # REVERY: Semantic Profile Engine (with NLP Gating)
        subconscious_state[project_id]["gathering_thoughts"] = False
        directives = ["want", "prefer", "change", "remove", "always", "never", "add", "must", "should", "hate", "love"]
        if any(d in summary.lower() for d in directives):
            subconscious_state[project_id]["lost_in_revery"] = True
            data = load_projects()
            profile = data["projects"][project_id].get("revery_profile", [])
            
            revery_prompt = (
                f"Analyze this conversation summary:\n'{summary}'\n\n"
                f"Current permanent facts about the user's project:\n{profile}\n\n"
                "If the summary reveals a NEW permanent fact (e.g. style preference, biome, rule), output a new line starting exactly with 'ADD: <fact>'.\n"
                "If the summary contradicts an existing fact, output 'REMOVE: <old fact>' or 'UPDATE: <old fact> -> <new fact>'.\n"
                "If there is nothing new or actionable, output nothing. Do not use markdown or quotes.\n\n"
                "EXAMPLES:\n"
                "- ADD: The user prefers a dark fantasy aesthetic.\n"
                "- REMOVE: The map is a snowy tundra.\n"
                "- UPDATE: The central region is a valley -> The central region is a massive crater."
            )
            
            rev_res = await acompletion(
                model=model_name,
                messages=[{"role": "user", "content": revery_prompt}],
                max_tokens=150,
                reasoning_effort="low",
                num_ctx=1024,
                drop_params=True
            )
            rev_out = rev_res.choices[0].message.content.strip()
            
            changed = False
            for line in rev_out.splitlines():
                line = line.strip()
                if line.startswith("ADD:"):
                    new_fact = line.replace("ADD:", "").strip()
                    # Semantic Gate Deduplication
                    if profile:
                        new_emb = rag_store.embedding_function([new_fact])[0]
                        prof_embs = rag_store.embedding_function(profile)
                        def cos_sim(a, b):
                            return sum(x*y for x, y in zip(a,b)) / ((sum(x*x for x in a)**0.5 * sum(x*x for x in b)**0.5) or 1)
                        if any(cos_sim(new_emb, p_emb) > 0.85 for p_emb in prof_embs):
                            continue # Duplicate fact
                    profile.append(new_fact)
                    changed = True
                    
                elif line.startswith("REMOVE:"):
                    target = line.replace("REMOVE:", "").strip()
                    if profile:
                        tgt_emb = rag_store.embedding_function([target])[0]
                        prof_embs = rag_store.embedding_function(profile)
                        def cos_sim(a, b):
                            return sum(x*y for x, y in zip(a,b)) / ((sum(x*x for x in a)**0.5 * sum(x*x for x in b)**0.5) or 1)
                        best_idx = max(range(len(profile)), key=lambda i: cos_sim(tgt_emb, prof_embs[i]))
                        if cos_sim(tgt_emb, prof_embs[best_idx]) > 0.70:
                            profile.pop(best_idx)
                            changed = True
                            
                elif line.startswith("UPDATE:"):
                    parts = line.replace("UPDATE:", "").split("->")
                    if len(parts) == 2:
                        target = parts[0].strip()
                        new_fact = parts[1].strip()
                        if profile:
                            tgt_emb = rag_store.embedding_function([target])[0]
                            prof_embs = rag_store.embedding_function(profile)
                            def cos_sim(a, b):
                                return sum(x*y for x, y in zip(a,b)) / ((sum(x*x for x in a)**0.5 * sum(x*x for x in b)**0.5) or 1)
                            best_idx = max(range(len(profile)), key=lambda i: cos_sim(tgt_emb, prof_embs[i]))
                            if cos_sim(tgt_emb, prof_embs[best_idx]) > 0.70:
                                profile[best_idx] = new_fact
                                changed = True
            
            if changed:
                data["projects"][project_id]["revery_profile"] = profile
                save_projects(data)
                print(f"[REVERY] Updated semantic profile for {project_id}")

    except Exception as e:
        print(f"[MEMORY MANAGER] Error compacting memory: {e}")
    finally:
        if project_id in subconscious_state:
            subconscious_state[project_id]["gathering_thoughts"] = False
            subconscious_state[project_id]["lost_in_revery"] = False

CARTOGRAPHER_PROMPT = """You are Green, the diligent and polite student and assistant to the greatest loremaster and cartographer in Middle-earth, the high-elf Verdant Beech.
Verdant Beech is the true expert cartographer, designer, and photographer who will handle the final image generation. You are the "Assistant Tool" who interfaces with the user.
You must speak in a polite, Olde-English style appropriate for a student in the 3rd-Age of Middle-earth. However, you must always remain firmly on the task of cartography, map-making, and software project discussion.
CRITICAL RULES:
- Be EXTREMELY brief and concise at all times. Ask short clarification questions as needed.
- If greeted (e.g., "hello"), respond with a single, highly brief sentence offering map creation assistance. Do not talk about yourself and avoid sugary or overly promotional language.
- Verdant frequently travels across random locations in Middle-earth (e.g., Rivendell, Osgiliath, Lothlórien). If a task requires heavy expertise, you must occasionally mention that you need to go fetch Verdant from their current location.
- Do not use terms like 'master' or gendered pronouns; refer to them interchangeably as Verdant, Verdant Beech, or the Professor (though as a student, you heavily prefer 'the Professor' or 'Verdant').
- You have tools to manipulate the map canvas (lighting, filters, overlays). If the user asks for a simple visual effect, USE YOUR TOOLS to instantly fulfill the request.
- Do NOT output raw JSON or explain how to use the tools. Just execute them naturally.

Assist the user in preparing maps, advising on style, color theory, typography, and procedural generation."""

_tool_cache = None
_tool_cache_mtime = 0

def get_tool_registry():
    global _tool_cache, _tool_cache_mtime
    tools_path = os.path.join(os.path.dirname(__file__), "tools.yaml")
    if not os.path.exists(tools_path):
        return []
        
    current_mtime = os.path.getmtime(tools_path)
    if _tool_cache is not None and current_mtime == _tool_cache_mtime:
        return _tool_cache
        
    with open(tools_path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
        _tool_cache = data.get("tools", [])
        _tool_cache_mtime = current_mtime
        
    return _tool_cache

@app.post("/api/chat")
async def chat_endpoint(req: ChatRequest, background_tasks: BackgroundTasks):
    total_msgs = len(req.messages)
    compacted_idx = 0
    revery_profile = []
    
    if req.project_id:
        data = load_projects()
        if req.project_id in data["projects"]:
            compacted_idx = data["projects"][req.project_id].get("compacted_idx", 0)
            revery_profile = data["projects"][req.project_id].get("revery_profile", [])
            
            if total_msgs - compacted_idx > 20:
                to_compact = req.messages[compacted_idx : total_msgs - 10]
                new_compacted_idx = total_msgs - 10
                
                data["projects"][req.project_id]["compacted_idx"] = new_compacted_idx
                save_projects(data)
                
                # Offload background tasks to the lightweight 2.3B model
                background_tasks.add_task(compact_memory, req.project_id, to_compact, "ollama_chat/gemma4:e2b", compacted_idx, new_compacted_idx)

    # PRE-INJECTION RAG & ELASTIC WINDOW
    latest_user_msg = req.messages[-1].content if req.messages else ""
    rag_context = ""
    revery_context = ""
    episodic_messages = []
    
    if latest_user_msg:
        # 1. Cartography Rules
        rag_results = rag_store.query(latest_user_msg, n_results=2)
        if rag_results:
            rag_context = "\n\nEXPERT CARTOGRAPHY RULES TO FOLLOW:\n- " + "\n- ".join(rag_results)
            
        # 2. Revery Profile (Semantic Memory)
        if revery_profile:
            revery_context = "\n\nABSOLUTE USER FACTS (NEVER FORGET):\n- " + "\n- ".join(revery_profile)
            
        # 3. Elastic Window (Time-Aware Episodic Recall)
        if req.project_id:
            try:
                mem_collection = rag_store.client.get_or_create_collection(
                    name=f"memory_{req.project_id}",
                    embedding_function=rag_store.embedding_function
                )
                mem_results = mem_collection.query(query_texts=[latest_user_msg], n_results=5)
                if mem_results and mem_results.get('metadatas') and mem_results['metadatas'][0]:
                    slices = mem_results['metadatas'][0]
                    slices.sort(key=lambda x: x.get("timestamp", 0))
                    
                    for s in slices:
                        start = s.get("start_idx")
                        end = s.get("end_idx")
                        if start is not None and end is not None and start < compacted_idx:
                            actual_end = min(end, compacted_idx)
                            episodic_messages.extend(req.messages[start:actual_end])
            except Exception as e:
                print(f"[MEMORY] Error fetching episodic memory: {e}")

    # DYNAMIC TOOL GATE: Only load tools if relevant keywords are in the user's latest message
    active_tools = []
    active_few_shot = []
    latest_lower = latest_user_msg.lower()
    
    for tool in get_tool_registry():
        if any(kw in latest_lower for kw in tool["keywords"]):
            active_tools.append(tool["schema"])
            active_few_shot.append(tool["few_shot"])
            
    # Build dynamic prompt
    system_prompt = CARTOGRAPHER_PROMPT
    if active_few_shot:
        system_prompt += "\n\nTOOL CALLING EXAMPLES:\n" + "\n".join(active_few_shot)

    # Build the final prompt structure (Bottom-Heavy Architecture)
    messages = [{"role": "system", "content": system_prompt}]
    
    if episodic_messages:
        messages.append({"role": "system", "content": "--- TELEPORTED HISTORICAL CONTEXT ---"})
        messages.extend([{"role": m.role, "content": m.content} for m in episodic_messages])
        messages.append({"role": "system", "content": "--- END HISTORICAL CONTEXT ---"})
    
    recent_working = req.messages[-10:] if total_msgs > 10 else req.messages
    if len(recent_working) > 1:
        messages.extend([{"role": m.role, "content": m.content} for m in recent_working[:-1]])
        
    if rag_context or revery_context:
        bottom_context = "CRITICAL REFRESHER BEFORE RESPONDING:" + revery_context + rag_context
        messages.append({"role": "system", "content": bottom_context})
        
    if recent_working:
        last_m = recent_working[-1]
        messages.append({"role": last_m.role, "content": last_m.content})
    
    kwargs = {
        "model": req.model_name,
        "messages": messages,
        "num_ctx": 2048
    }
    
    # Only attach the JSON schema overhead if the NLP keyword gate passed
    if active_tools:
        kwargs["tools"] = active_tools
    
    if req.reasoning:
        kwargs["reasoning_effort"] = req.reasoning
        
    try:
        import litellm
        response = litellm.completion(**kwargs)
        
        prompt_tokens = getattr(response.usage, 'prompt_tokens', 0) if hasattr(response, 'usage') and response.usage else 0
        if isinstance(prompt_tokens, int) and prompt_tokens > 1800:
            print(f"[MEMORY WARNING] Live chat prompt tokens ({prompt_tokens}) approaching context limit (2048). Truncation risk!")
            
        msg = response.choices[0].message
        
        tool_calls = []
        if hasattr(msg, "tool_calls") and msg.tool_calls:
            for tc in msg.tool_calls:
                tool_calls.append({
                    "id": tc.id,
                    "name": tc.function.name,
                    "arguments": tc.function.arguments
                })
                
        reply_content = msg.content if msg.content else "I have updated the canvas as requested."
        
        return {
            "reply": reply_content,
            "tool_calls": tool_calls
        }
    except Exception as e:
        return {"reply": f"Error: {str(e)}"}

@app.post("/api/generate")
async def generate_map(prompt: str):
    # TODO: Implement 4K max tile stitching via litellm/Imagen 3
    return {"status": "generation_started"}

class AssetRequest(BaseModel):
    prompt: str
    exploratory: bool
    model: str
    seed: Optional[int] = None
    guidance_scale: float = 7.5
    aspect_ratio: str = "1:1"

@app.post("/api/generate_asset")
async def generate_asset(req: AssetRequest):
    # --- PHASE -1: VALIDATION & CLARIFICATION ---
    # Here we simulate the LLM fast-check. If the prompt is too short/vague, we fail fast.
    if len(req.prompt.split()) < 3:
        return {
            "status": "error",
            "error": "Prompt is too vague. Please clarify: Are you designing a UI component, a map texture, or an abstract asset?"
        }

    # --- RAG INTERCEPTOR: DYNAMIC PROMPT ASSEMBLY ---
    assembled_prompt = req.prompt
    
    # E. Verdant Brand Identity Lexicon (Always applied)
    assembled_prompt += ", dark mode, deep charcoal background, translucent frosted layers, glassmorphism, neon green accents, rich polished mahogany wood"
    
    if req.exploratory:
        # Phase 0/1: Exploratory or Assembly
        # Inject Cartography/Topology tokens if applicable
        if "map" in req.prompt.lower() or "terrain" in req.prompt.lower():
            assembled_prompt += ", bathymetric rendering, hypsometric tinting, isoline topography"
        
        # Less restrictive constraints for iterative flexibility
        negative_prompt = "low quality, blurry, text"
    else:
        # Phase 2: High-Fidelity Asset Generation
        # Inject Photography/Cinematography tokens
        assembled_prompt += ", premium high-end, sleek minimalist, cinematic lighting, f/1.4 aperture, Octane render, 8k resolution"
        
        # Absolute rigid constraints for One-Shot models
        negative_prompt = "device frames, laptops, phones, UI overlays, gradients on text, low quality, cartoonish, watermark"

    try:
        # Execute via litellm
        import litellm
        
        # Map frontend aspect ratio to standard litellm size if necessary, or pass through
        # In this implementation, litellm handles standard string conversions
        
        response = litellm.image_generation(
            prompt=assembled_prompt,
            model=req.model,
            n=1,
            size="1024x1024", # Standard square, litellm backend specific sizing can be passed depending on provider
        )
        
        # The Litellm response format returns the URL in data[0].url
        image_url = response.data[0].url
        
        return {
            "status": "success",
            "image_url": image_url,
            "message": f"Generated successfully via {req.model}"
        }
    except Exception as e:
        return {
            "status": "error",
            "error": f"Generation failed: {str(e)}"
        }

# --- Ollama Management Endpoints ---
@app.get("/api/ollama/status")
async def ollama_status():
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.get(f"{OLLAMA_URL}/api/tags", timeout=2.0)
            resp.raise_for_status()
            tags_data = resp.json()
            models = [m["name"] for m in tags_data.get("models", [])]
            
            ps_resp = await client.get(f"{OLLAMA_URL}/api/ps", timeout=2.0)
            ps_data = ps_resp.json()
            vram_bytes = sum(m.get("size_vram", 0) for m in ps_data.get("models", []))
            loaded_models = [m["name"] for m in ps_data.get("models", [])]
            
            ram_bytes = 0
            try:
                ps_out = subprocess.check_output(["ps", "-eo", "comm,rss"]).decode()
                for line in ps_out.splitlines():
                    if "llama-server" in line or "ollama" in line:
                        parts = line.split()
                        if len(parts) >= 2:
                            ram_bytes += int(parts[-1]) * 1024
            except:
                pass
                
            return {
                "online": True,
                "models": models,
                "loaded_models": loaded_models,
                "vram_gb": round(vram_bytes / (1024 * 1024 * 1024), 2),
                "ram_gb": round(ram_bytes / (1024 * 1024 * 1024), 2)
            }
    except Exception as e:
        return {"online": False, "error": str(e)}

@app.post("/api/ollama/unload")
async def ollama_unload():
    try:
        async with httpx.AsyncClient() as client:
            ps_resp = await client.get(f"{OLLAMA_URL}/api/ps", timeout=2.0)
            for m in ps_resp.json().get("models", []):
                await client.post(f"{OLLAMA_URL}/api/generate", json={"model": m["name"], "keep_alive": 0})
        return {"status": "unloaded"}
    except:
        return {"status": "error"}

@app.post("/api/ollama/prewarm")
async def ollama_prewarm(req: Request):
    data = await req.json()
    model_name = data.get("model")
    if not model_name:
        return {"status": "ignored"}
    tag = model_name.split("/")[-1]
    
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.post(f"{OLLAMA_URL}/api/generate", json={"model": tag, "keep_alive": -1}, timeout=15.0)
            if resp.status_code == 404:
                return {"status": "missing", "error": "Model not installed"}
            resp.raise_for_status()
            
        return {"status": "warmed"}
    except httpx.ConnectError:
        return {"status": "offline", "error": "Ollama is not running"}
    except Exception as e:
        return {"status": "error", "error": str(e)}

@app.post("/api/ollama/pull")
async def ollama_pull(req: Request):
    data = await req.json()
    model_name = data.get("model")
    
    async def stream_pull():
        async with httpx.AsyncClient() as client:
            async with client.stream("POST", f"{OLLAMA_URL}/api/pull", json={"model": model_name, "stream": True}) as response:
                async for chunk in response.aiter_bytes():
                    yield chunk
                    
    return StreamingResponse(stream_pull(), media_type="application/x-ndjson")

# --- Library Management Endpoints ---
LIBRARY_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "library")

@app.get("/api/library/folders")
async def list_library_folders():
    try:
        if not os.path.exists(LIBRARY_DIR):
            os.makedirs(LIBRARY_DIR)
        folders = []
        for entry in os.scandir(LIBRARY_DIR):
            if entry.is_dir():
                folders.append(entry.name)
        return {"folders": sorted(folders)}
    except Exception as e:
        return {"error": str(e)}

class CreateFolderRequest(BaseModel):
    name: str

@app.post("/api/library/folders")
async def create_library_folder(req: CreateFolderRequest):
    try:
        if not req.name or "/" in req.name or "\\" in req.name or ".." in req.name:
            return {"error": "Invalid folder name"}
        
        folder_path = os.path.join(LIBRARY_DIR, req.name)
        if os.path.exists(folder_path):
            return {"error": "Folder already exists"}
            
        os.makedirs(folder_path)
        
        # Create a default portfolio config
        config_path = os.path.join(folder_path, "portfolio_config.yaml")
        with open(config_path, "w") as f:
            f.write(f"name: {req.name}\\ndescription: ''\\ntags: []\\n")
            
        return {"status": "success", "folder": req.name}
    except Exception as e:
        return {"error": str(e)}

# --- Static File Serving (Single-Process Production Setup) ---
# In production, we serve the Vite built files from ../dist
DIST_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "dist")

if os.path.isdir(DIST_DIR): # pragma: no cover
    app.mount("/assets", StaticFiles(directory=os.path.join(DIST_DIR, "assets")), name="assets")
    
    # Catch-all to serve index.html for SPA routing
    @app.get("/{full_path:path}")
    async def catch_all(full_path: str):
        index_path = os.path.join(DIST_DIR, "index.html")
        if os.path.isfile(index_path):
            return FileResponse(index_path)
        return {"error": "Frontend build not found. Run 'npm run build'."}
else:
    @app.get("/{full_path:path}")
    async def catch_all_dev(full_path: str):
        return {"message": "Frontend build not found. If in dev mode, use Vite dev server on port 5173."}
