from fastapi import FastAPI, Request
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse, StreamingResponse
from fastapi.middleware.cors import CORSMiddleware
import os
from pydantic import BaseModel
from typing import List
import litellm
import yaml
import httpx
import subprocess
import asyncio

app = FastAPI(title="Verdant Beech API", description="Backend for the Cartography Agent")
OLLAMA_URL = "http://localhost:11434"

# Allow CORS for development (Vite dev server)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict this
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- API Endpoints ---
@app.get("/api/health")
async def health_check():
    return {"status": "ok", "service": "verdant-beech"}

# --- YAML Model Configuration ---
MODELS_YAML_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "models.yaml")
DEFAULT_MODELS_YAML = """# Verdant Beech - Model Configuration
# This file is automatically generated. Add or modify LiteLLM compatible models here.

assistant_models:
  - id: "gemini/gemini-3.5-flash"
    label: "Gemini 3.5 Flash"
  - id: "gemini/gemini-3.1-pro"
    label: "Gemini 3.1 Pro"
  - id: "ollama_chat/gemma-4-e4b-qat"
    label: "Gemma 4 (4.5B)"
  - id: "ollama_chat/gemma-4-e2b-qat"
    label: "Gemma 4 (2.3B)"
  # Template for other providers:
  # - id: "groq/llama3-8b-8192"
  #   label: "Llama 3 8B (Groq)"
  # - id: "anthropic/claude-3-haiku-20240307"
  #   label: "Claude 3 Haiku"
  # - id: "huggingface/meta-llama/Meta-Llama-3-8B-Instruct"
  #   label: "Llama 3 8B (HF)"

image_models:
  - id: "vertex_ai/imagen-3.0-generate"
    label: "Imagen 3 (Vertex AI)"
  # Template for other image providers:
  # - id: "dall-e-3"
  #   label: "DALL-E 3 (OpenAI)"
  # - id: "stabilityai/stable-diffusion-3"
  #   label: "Stable Diffusion 3"
"""

def ensure_models_yaml():
    if not os.path.exists(MODELS_YAML_PATH):
        with open(MODELS_YAML_PATH, "w") as f:
            f.write(DEFAULT_MODELS_YAML)

ensure_models_yaml()

@app.get("/api/models")
async def get_models():
    try:
        with open(MODELS_YAML_PATH, "r") as f:
            return yaml.safe_load(f)
    except Exception as e:
        return {"error": str(e)}

# --- Agent / Litellm Stubs ---
class ChatMessage(BaseModel):
    role: str
    content: str

class ChatRequest(BaseModel):
    messages: List[ChatMessage]
    model_name: str = "ollama_chat/gemma4:e4b"
    reasoning: str | None = None

CARTOGRAPHER_PROMPT = """You are Green, the diligent and polite student and assistant to the greatest loremaster and cartographer in Middle-earth, the high-elf Verdant Beech.
Verdant Beech is the true expert cartographer, designer, and photographer who will handle the final image generation. You are the "Assistant Tool" who interfaces with the user.
You must speak in a polite, Olde-English style appropriate for a student in the 3rd-Age of Middle-earth. However, you must always remain firmly on the task of cartography, map-making, and software project discussion.
CRITICAL RULES:
- Be EXTREMELY brief and concise at all times. Ask short clarification questions as needed.
- If greeted (e.g., "hello"), respond with a single, highly brief sentence offering map creation assistance. Do not talk about yourself and avoid sugary or overly promotional language.
- Verdant frequently travels across random locations in Middle-earth (e.g., Rivendell, Osgiliath, Lothlórien). If a task requires heavy expertise, you must occasionally mention that you need to go fetch Verdant from their current location.
- Do not use terms like 'master' or gendered pronouns; refer to them interchangeably as Verdant, Verdant Beech, or the Professor (though as a student, you heavily prefer 'the Professor' or 'Verdant').
Assist the user in preparing maps, advising on style, color theory, typography, and procedural generation."""

@app.post("/api/chat")
async def chat_endpoint(req: ChatRequest):
    messages = [{"role": "system", "content": CARTOGRAPHER_PROMPT}]
    messages.extend([{"role": m.role, "content": m.content} for m in req.messages])
    
    kwargs = {
        "model": req.model_name,
        "messages": messages
    }
    
    if req.reasoning:
        kwargs["reasoning_effort"] = req.reasoning
        
    try:
        response = litellm.completion(**kwargs)
        return {"reply": response.choices[0].message.content}
    except Exception as e:
        return {"reply": f"Error: {str(e)}"}

@app.post("/api/generate")
async def generate_map(prompt: str):
    # TODO: Implement 4K max tile stitching via litellm/Imagen 3
    return {"status": "generation_started"}

# --- Ollama Management Endpoints ---
@app.get("/api/ollama/status")
async def ollama_status():
    try:
        async with httpx.AsyncClient() as client:
            resp = await client.get(f"{OLLAMA_URL}/api/tags", timeout=2.0)
            resp.raise_for_status()
            tags_data = resp.json()
            models = [m["name"] for m in tags_data.get("models", [])]
            
            ps_resp = await client.get(f"{OLLAMA_URL}/api/ps", timeout=2.0)
            ps_data = ps_resp.json()
            vram_bytes = sum(m.get("size_vram", 0) for m in ps_data.get("models", []))
            loaded_models = [m["name"] for m in ps_data.get("models", [])]
            
            ram_bytes = 0
            try:
                ps_out = subprocess.check_output(["ps", "-eo", "comm,rss"]).decode()
                for line in ps_out.splitlines():
                    if "llama-server" in line or "ollama" in line:
                        parts = line.split()
                        if len(parts) >= 2:
                            ram_bytes += int(parts[-1]) * 1024
            except:
                pass
                
            return {
                "online": True,
                "models": models,
                "loaded_models": loaded_models,
                "vram_gb": round(vram_bytes / (1024 * 1024 * 1024), 2),
                "ram_gb": round(ram_bytes / (1024 * 1024 * 1024), 2)
            }
    except Exception as e:
        return {"online": False, "error": str(e)}

@app.post("/api/ollama/unload")
async def ollama_unload():
    try:
        async with httpx.AsyncClient() as client:
            ps_resp = await client.get(f"{OLLAMA_URL}/api/ps", timeout=2.0)
            for m in ps_resp.json().get("models", []):
                await client.post(f"{OLLAMA_URL}/api/generate", json={"model": m["name"], "keep_alive": 0})
        return {"status": "unloaded"}
    except:
        return {"status": "error"}

@app.post("/api/ollama/pull")
async def ollama_pull(req: Request):
    data = await req.json()
    model_name = data.get("model")
    
    async def stream_pull():
        async with httpx.AsyncClient() as client:
            async with client.stream("POST", f"{OLLAMA_URL}/api/pull", json={"model": model_name, "stream": True}) as response:
                async for chunk in response.aiter_bytes():
                    yield chunk
                    
    return StreamingResponse(stream_pull(), media_type="application/x-ndjson")

# --- Static File Serving (Single-Process Production Setup) ---
# In production, we serve the Vite built files from ../dist
DIST_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "dist")

if os.path.isdir(DIST_DIR):
    app.mount("/assets", StaticFiles(directory=os.path.join(DIST_DIR, "assets")), name="assets")
    
    # Catch-all to serve index.html for SPA routing
    @app.get("/{full_path:path}")
    async def catch_all(full_path: str):
        index_path = os.path.join(DIST_DIR, "index.html")
        if os.path.isfile(index_path):
            return FileResponse(index_path)
        return {"error": "Frontend build not found. Run 'npm run build'."}
else:
    @app.get("/{full_path:path}")
    async def catch_all_dev(full_path: str):
        return {"message": "Frontend build not found. If in dev mode, use Vite dev server on port 5173."}
